
server:
   port: 9100
spring:
   datasource:
      url: jdbc:mysql://thonx.cutnjbmkevif.ap-southeast-1.rds.amazonaws.com:3306/user
      username: admin
      password: Xuantho98
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
databaseName: user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      