server:
  port: 8083
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
#server:
#port: 8082
spring:
   datasource:
      url: jdbc:mysql://thonx.cutnjbmkevif.ap-southeast-1.rds.amazonaws.com:3306/product
      username: root
      password: root
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
databaseName: product
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/