server:
  port: 8087
management:
   endpoints:
      web:
         exposure:
            include: hystrix.streamx
#server:
#port: 8082
spring:
   datasource:
      url: thonx.cutnjbmkevif.ap-southeast-1.rds.amazonaws.com
      username: admin
      password: Xuantho98
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
databaseName: report
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/